#!/bin/sh

set -e

CACHE_TAR_PATH="${CACHE_TAR_PATH:-/usr/share/gsa-nodejs-build-dependencies/cache.tar.xz}"
YARN_CACHE_PATH="${YARN_CACHE_PATH:-$(yarnpkg cache dir)}"

if [ ! -d "$YARN_CACHE_PATH" ]; then
    echo "warning: non-existant yarn cache path $YARN_CACHE_PATH; creating it..." >&2
    mkdir -p "$YARN_CACHE_PATH"
fi

echo "extracting yarn offline cache at $YARN_CACHE_PATH ..." >&2
tar -C "$YARN_CACHE_PATH" -xJf "$CACHE_TAR_PATH"
